"""making database modelling updated

Revision ID: 08ab0c3fc5a6
Revises: f5c1dc71ed0d
Create Date: 2024-11-12 03:49:43.048646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08ab0c3fc5a6'
down_revision: Union[str, None] = 'f5c1dc71ed0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ##
