"""added users.secret_token_identifier, profile.date_of_birth, profile.location, profile.gender, removed users.gender, users.location, users.date_of_birth

Revision ID: 7642f6c45f81
Revises: a64418a510f9
Create Date: 2024-11-03 18:41:07.693789

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7642f6c45f81"
down_revision: Union[str, None] = "a64418a510f9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
from api.v1.enum_types import gender_type_enum


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "profiles",
        sa.Column("gender", gender_type_enum, nullable=True),
    )
    op.add_column("profiles", sa.Column("date_of_birth", sa.DateTime(), nullable=True))
    op.add_column(
        "profiles",
        sa.Column("location", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "users", sa.Column("secret_token_identifier", sa.String(), nullable=True)
    )
    op.drop_column("users", "gender")
    op.drop_column("users", "date_of_birth")
    op.drop_column("users", "location")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "location",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "date_of_birth", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "gender",
            sa.Enum("male", "female", name="gender_type_enum", check=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("users", "secret_token_identifier")
    op.drop_column("profiles", "location")
    op.drop_column("profiles", "date_of_birth")
    op.drop_column("profiles", "gender")
    # ### end Alembic commands ###
