"""added verification_requests.verifier_feedback, verification_requests.phto_url

Revision ID: 986d74c6bb2b
Revises: ecee9b465ac8
Create Date: 2024-11-10 11:36:25.133852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '986d74c6bb2b'
down_revision: Union[str, None] = 'ecee9b465ac8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_requests', sa.Column('verifier_feedback', sa.String(), nullable=True))
    op.add_column('verification_requests', sa.Column('photo_url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verification_requests', 'photo_url')
    op.drop_column('verification_requests', 'verifier_feedback')
    # ### end Alembic commands ###
