"""added stckiers.url, exchanged_stickers.quantity

Revision ID: f15bcac6097f
Revises: 37b64e692925
Create Date: 2024-11-12 09:28:09.260631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f15bcac6097f'
down_revision: Union[str, None] = '37b64e692925'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchanged_stickers', sa.Column('quantity', sa.Integer(), nullable=True))
    op.add_column('stickers', sa.Column('url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stickers', 'url')
    op.drop_column('exchanged_stickers', 'quantity')
    # ### end Alembic commands ###
